repos:

  # pip tools
  - repo: https://github.com/jazzband/pip-tools
    rev: 5.3.1
    hooks:
      # - id: pip-compile
      #   name: pip-compile app dir
      #   verbose: true
      #   args:
      #   - "app/requirements/base.txt"
      #   - "--output-file=compiled.txt"
      #   files: ^app/requirements/base\.(in|txt)$

      - id: pip-compile
        name: pip-compile root dir
        verbose: true
        args:
        - "root.txt"
        - "--output-file=compiled.txt"
        files: ^root\.txt$

